// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmnz3ncaiAUYJzlXXmBFRX2z6MAFWMU5E',
    appId: '1:789923558727:web:5256ef1690a7f1fe368862',
    messagingSenderId: '789923558727',
    projectId: 'movie-hub-6335d',
    authDomain: 'movie-hub-6335d.firebaseapp.com',
    storageBucket: 'movie-hub-6335d.firebasestorage.app',
    measurementId: 'G-EC5M2KQBVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9G5A98OBNncYIrri2XjgGwK8BaZJE4sE',
    appId: '1:789923558727:android:494ad15be908f187368862',
    messagingSenderId: '789923558727',
    projectId: 'movie-hub-6335d',
    storageBucket: 'movie-hub-6335d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzLRZKc4ymSRhGC1NUQulrQmsDZZZwzVA',
    appId: '1:789923558727:ios:a3aadfef23287b54368862',
    messagingSenderId: '789923558727',
    projectId: 'movie-hub-6335d',
    storageBucket: 'movie-hub-6335d.firebasestorage.app',
    iosBundleId: 'com.example.movieHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzLRZKc4ymSRhGC1NUQulrQmsDZZZwzVA',
    appId: '1:789923558727:ios:a3aadfef23287b54368862',
    messagingSenderId: '789923558727',
    projectId: 'movie-hub-6335d',
    storageBucket: 'movie-hub-6335d.firebasestorage.app',
    iosBundleId: 'com.example.movieHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmnz3ncaiAUYJzlXXmBFRX2z6MAFWMU5E',
    appId: '1:789923558727:web:ee054f5181f32152368862',
    messagingSenderId: '789923558727',
    projectId: 'movie-hub-6335d',
    authDomain: 'movie-hub-6335d.firebaseapp.com',
    storageBucket: 'movie-hub-6335d.firebasestorage.app',
    measurementId: 'G-PKZTE0P25H',
  );
}